%> @file   FacesForcingAssemblyPoroelasticity.m
%> @author Mattia Corti
%> @date   30 May 2026
%> @brief Assembly of the forcing vectors associated with face's integrals for
%> poroelasticity equation.
%>
%==========================================================================
%> @section classFacesForcingAssemblyPoroelasticity Class description
%==========================================================================
%> @brief            Assembly of the forcing vectors associated with face's
%> integrals for poroelasticity equation.
%>
%> @param Data       Struct with problem's data
%> @param femregion  Finite Element struct (s0.5 * mu * face.nx CreateDOF.m)
%> @param Forcing    Forcing struct (to be modified)
%> @param face       Face struct containing the quadrature nodes, penalty and bases
%> @param AssembInfo Struct containing specific information for the
%> assembly procedure
%>
%> @retval Forcing   Forcing struct
%>                   
%==========================================================================

function [Forcing] = FacesForcingAssemblyPoroelasticity(Data, femregion, Forcing, face, AssembInfo)
   
    %% Dirichlet boundary faces
    if face.neigh_ie == -1

        ie   = face.ie;
        iedg = face.iedg;

        % Evaluation of physical parameters
        mu      = Data.mu{femregion.id_phys(ie)}(face.xq,face.yq);
        lam     = Data.lam{femregion.id_phys(ie)}(face.xq,face.yq);
        beta    = Data.beta{femregion.id_phys(ie)}(face.xq,face.yq);
        m       = Data.m{femregion.id_phys(ie)}(face.xq,face.yq);
        
        gD1 = Data.DirBCPoro_up{1}(face.xq,face.yq);
        gD2 = Data.DirBCPoro_up{2}(face.xq,face.yq);
        hD1 = Data.DirBCPoro_wp{1}(face.xq,face.yq);
        hD2 = Data.DirBCPoro_wp{2}(face.xq,face.yq);
       
        % Vector assembling
        Forcing.F1_D_loc(1:femregion.nbases(ie),1) = Forcing.F1_D_loc(1:femregion.nbases(ie),1) ...
            - 2 * (face.ds .* (0.5 * (lam+2*mu) * face.nx .* face.gradedgeqx + 0.5 * mu * face.ny .* face.gradedgeqy))' *gD1 ...
            - 2 * (face.ds .* (0.5 * lam * face.ny .* face.gradedgeqx + 0.5 * mu * face.nx .* face.gradedgeqy))' *gD2 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (lam+2*mu) .* face.phiedgeq)' * gD1;

        Forcing.F2_D_loc(1:femregion.nbases(ie),1) = Forcing.F2_D_loc(1:femregion.nbases(ie),1) ...
            - 2 * (face.ds .* (0.5 * mu * face.ny .* face.gradedgeqx + 0.5 * lam * face.nx .* face.gradedgeqy))' *gD1 ...
            - 2 * (face.ds .* (0.5 * mu * face.nx .* face.gradedgeqx + 0.5 * (lam+2*mu) * face.ny .* face.gradedgeqy))' *gD2 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (lam+2*mu) .* face.phiedgeq)' * gD2;

        Forcing.F1_D_loc(1:femregion.nbases(ie),1) = Forcing.F1_D_loc(1:femregion.nbases(ie),1) - (face.ds .* (beta .* beta .*m .* face.gradedgeqx))' * (gD1*face.nx + gD2*face.ny) ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .* beta .*m .* face.nx .* face.nx .* face.phiedgeq ))' * gD1 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .* beta .*m .* face.nx .* face.ny .* face.phiedgeq ))' * gD2 ...
            - (face.ds .* (beta .*m .* face.gradedgeqx))' * (hD1*face.nx + hD2*face.ny)...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .*m .* face.nx .* face.nx .* face.phiedgeq ))' * hD1 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .*m .* face.nx .* face.ny .* face.phiedgeq ))' * hD2;

        Forcing.F2_D_loc(1:femregion.nbases(ie),1) = Forcing.F2_D_loc(1:femregion.nbases(ie),1) ...
            - (face.ds .* (beta .* beta .*m .* face.gradedgeqy))' * (gD1*face.nx + gD2*face.ny) ... 
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .* beta .*m .* face.nx .* face.ny .* face.phiedgeq ))' * gD1 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .* beta .*m .* face.ny .* face.ny .* face.phiedgeq ))' * gD2 ...
            - (face.ds .* (beta .*m .* face.gradedgeqy))' * (hD1*face.nx + hD2*face.ny) ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .*m .* face.nx .* face.ny .* face.phiedgeq ))' * hD1 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .*m .* face.ny .* face.ny .* face.phiedgeq ))' * hD2;

        Forcing.G1_D_loc(1:femregion.nbases(ie),1) = Forcing.G1_D_loc(1:femregion.nbases(ie),1) ...
            - (face.ds .* (beta .*m .* face.gradedgeqx))' * (gD1*face.nx + gD2*face.ny) ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .*m .* face.nx .* face.nx .* face.phiedgeq ))' * gD1 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .*m .* face.nx .* face.ny .* face.phiedgeq ))' * gD2 ...
            - (face.ds .* (m .* face.gradedgeqx))' * (hD1*face.nx + hD2*face.ny) ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (m .* face.nx .* face.nx .* face.phiedgeq ))' * hD1 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (m .* face.nx .* face.ny .* face.phiedgeq ))' * hD2;

        Forcing.G2_D_loc(1:femregion.nbases(ie),1) = Forcing.G2_D_loc(1:femregion.nbases(ie),1) ...
            - (face.ds .* (beta .*m .* face.gradedgeqy))' * (gD1*face.nx + gD2*face.ny) ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .*m .* face.nx .* face.ny .* face.phiedgeq ))' * gD1 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (beta .*m .* face.ny .* face.ny .* face.phiedgeq ))' * gD2...
            - (face.ds .* (m .* face.gradedgeqy))' * (hD1*face.nx + hD2*face.ny) ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (m .* face.nx .* face.ny .* face.phiedgeq ))' * hD1 ...
            + face.penalty_geom.harm(iedg) * (face.ds .* (m .* face.ny .* face.ny .* face.phiedgeq ))' * hD2;

    end

end
